[package]
name = "rust-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
env_logger = "0.11.5"
reqwest = { version = "0.11.9", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
